name: C++ CI Serial Programs

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: [windows-latest]

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        path: .\Arduino-Source
    - uses: actions/checkout@v2
      with:
        repository: 'PokemonAutomation/Packages'
        path: .\Packages
    - name: Add msbuild to PATH
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.10'
        arch: 'win64_msvc2017_64'
    - name: Generate binaries
      run: |
        cd Arduino-Source\SerialPrograms\
        mkdir bin
        cd bin\
        cmake ..\ -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH=C:\Qt\5.12.10\msvc2019_64\
        MSBuild.exe .\SerialPrograms.vcxproj /p:Configuration=${{ matrix.config }} /p:Platform=x64
    - name: Copy resources
      run: |
        robocopy Packages\SerialPrograms\Resources\                         Output\Resources\ /s
        robocopy Packages\PABotBase\PABotBase-Switch\                       Output\PABotBase\ /s
        robocopy Arduino-Source\SerialPrograms\bin\                         Output\Binaries\ libcrypto-1_1-x64.dll libssl-1_1-x64.dll Sleepy.dll tesseractPA.dll
        robocopy Arduino-Source\SerialPrograms\bin\${{ matrix.config }}\    Output\Binaries\ SerialPrograms.exe
        exit 0
    - uses: actions/upload-artifact@v2
      with:
        name: Serial Programs for windows ${{ matrix.config }}
        path: Output\
