name: C++ CI Serial Programs

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up MinGW
      if: contains( matrix.os, 'windows')
      uses: egor-tensin/setup-mingw@v2
    - name: Install Qt
      if: contains( matrix.os, 'windows')
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.10'
        arch: 'win64_mingw73'
    - name: Install Qt
      if: contains( matrix.os, 'macOS')
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.10'
    - name: C++ generation
      run: |
        cd SerialPrograms
        qmake
        make
    - name: Generate windows package
      if: contains( matrix.os, 'windows')
      run: |
        mkdir package
        move SerialPrograms/release/SerialPrograms.exe package/
        move SerialPrograms/libtesseractc.dll package/
        windeployqt ./package/SerialPrograms.exe
    - uses: actions/upload-artifact@v2
      if: contains( matrix.os, 'windows')
      with:
        name: Serial Programs for windows
        path: package/
